name    'wildajet-account'
version '0.0.2'
source 'UNKNOWN'
author 'Jet Wilda'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib', '3.2.0'
